### ISSUE TITLE
Can't find "GAN" in config

### ISSUE THREAD

**Issue by yepw** [jangerritha/CycleIK#3]
Hi, thank you for making the tool open-source. I was trying to run the code and encountered an error. It seems like some items in the configuration file are missing. Maybe the items are not used. 

what I ran
```
from cycleik_pytorch import CycleIK
cycleik = CycleIK(robot="nicol", cuda_device='0', verbose=True, chain="right_arm")
```

output on screen
```
data path: /home/yeping/cycleik_ws/CycleIK/cycleik_pytorch
-0.2
-0.5249999999999999
-0.8
-1.1
[-0.525  0.21  -1.1  ]
[0.325 0.69  0.3  ]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yeping/cycleik_ws/CycleIK/cycleik_pytorch/predictor.py", line 71, in __init__
    noise_vector_size=self.config["GAN"]["architecture"]["noise_vector_size"],
                      ~~~~~~~~~~~^^^^^^^
KeyError: 'GAN'
```

**Comment by jangerritha** [comment]
Thank you for the bug report, you are correct that the GAN is not used here but the application tries to load it.

Added use_gan flag to avoid loading the GAN in predictor.py

Added config for the GAN (just to avoid errors)

I updated dev and main branches.

Can you verify that it works for you?

**Comment by yepw** [comment]
Thank you for the quick reply. I have pulled the latest commit and it works. 

However, it seems that I can make it work only on the nicol robot. I tried to generate a motion for a panda robot. I think I might miss something, e.g., I am incorrectly using nicol's model for the panda robot. Here is my code
```
import numpy as np
from cycleik_pytorch import CycleIK
import csv

cycleik = CycleIK(robot="panda", cuda_device='0', verbose=True, chain="arm")

start_pose = np.array([0.5, -0.3, 0.39, 1, 0, 0, 0])
target_pose = np.array([0.5, 0.3, 0.395, 1, 0, 0, 0])
control_points = np.array([np.array([0.4, -0.1, 0.2, 1, 0, 0, 0]),
                           np.array([0.4, 0.1, 0.2, 1, 0, 0, 0])])

bezier_curve = cycleik.generate_cubic_bezier_trajectory(start_pose=start_pose,
                                                        target_pose=target_pose,
                                                        control_points=control_points,
                                                        points=100)

joint_trajectory, _, _, _ = cycleik.inverse_kinematics(bezier_curve, calculate_error=True)

print(joint_trajectory)
```
The robot barely moves in the output motion: 
```
[[-0.09495622 -0.007591    0.07625954 -1.5899007   0.0177541   1.8194971
  -0.08836585]
 [-0.09495399 -0.00759087  0.07626963 -1.5898988   0.01775302  1.8194985
  -0.08836985]
 [-0.09495171 -0.0075907   0.0762796  -1.5898969   0.01775194  1.8194999
  -0.08837376]
 [-0.09494939 -0.00759051  0.0762894  -1.5898951   0.01775085  1.8195013
  -0.08837759]
 ...
 [-0.09450538 -0.00742358  0.07653415 -1.5896995   0.01763885  1.8196816
  -0.08836251]
 [-0.09449819 -0.00742018  0.07652941 -1.5896972   0.01763748  1.819684
  -0.08835833]
 [-0.09449095 -0.00741673  0.07652452 -1.589695    0.0176361   1.8196864
  -0.08835406]]
```

**Comment by jangerritha** [comment]
@yepw to auto-download weights for the predictor.py application, the config needs to hold a `pretrained_weights:` tag with a correct link in the config. 

I added this tag for the IKNets of the other robots. 

NICO robot currently has a bug, I need to fix that later.

Following models are now available for auto-download: 

- NICOL (right arm chain)
- Fetch (arm + torso lift)
- Panda (arm)
- Valkyrie (right arm)

If you want to use a different chain the network needs to be trained for that, meaning you have to collect data from Moveit then run our training script. (Will extend the Readme about running the whole data aggregation + training next week)

**Comment by yepw** [comment]
Thanks, I just tried the panda robot and it's working. 
![Screenshot from 2024-11-01 07-18-43](https://github.com/user-attachments/assets/e4fc443b-b7f5-4c12-8f90-5228a948aba8)
